import { Raleway } from "next/font/google";
import localFont from "next/font/local";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ttricordi = localFont({
  src: "./TT_Ricordi_Allegria_Trial_Regular.woff2",
  weight: "400",
  display: "swap",
  variable: "--font-ttricordi",
});

const raleway = Raleway({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "600", "700"],
  display: "swap",
  variable: "--font-raleway",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${ttricordi.variable} font-ttricordi font-normal text-base`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
